name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: CURL no site $URL_TEST
        run: curl $URL_TEST
        env:
          URL_TEST: http://globo.com
